spring.datasource.url=jdbc:hsqldb:mem:testdb
spring.datasource.username=SA
spring.datasource.password=
#
management.metrics.export.influx.token=apiv3_1yH1iS6W1IHNUMrm5IpYHp366z48HUoqRPcxOMtNGq4W3Wv6-p4scICMIcjm3oJ7Gxw-9Hew53PBVQIfL-6tWQ
management.metrics.export.influx.uri=localhost:8181/api/v3
#