// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.30.2

package com.demo.newfeature.web.grpc.proto;

public interface AddOneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddOneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 intValue = 20;</code>
   * @return The intValue.
   */
  int getIntValue();

  /**
   * <code>float decValue = 30;</code>
   * @return The decValue.
   */
  float getDecValue();
}
