// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

// Protobuf Java Version: 3.25.8
package com.demo.newfeature.web.grpc.proto;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddOneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddOneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OneVO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OneVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\"A\n\rAddOneRequest\022\014\n\004name\030\001 " +
      "\001(\t\022\020\n\010intValue\030\024 \001(\005\022\020\n\010decValue\030\036 \001(\002\"" +
      ",\n\rSearchRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005token\030" +
      "\002 \001(\t\"\262\001\n\005OneVO\022\n\n\002id\030\n \001(\t\022\014\n\004name\030\024 \001(" +
      "\t\022\027\n\nsubmitTime\030\036 \001(\003H\000\210\001\001\022\020\n\010intValue\030(" +
      " \001(\005\022\020\n\010decValue\0302 \001(\002\022\033\n\006status\030< \001(\0162\013" +
      ".StatusType\022\023\n\013createdDate\030F \001(\003\022\021\n\tcrea" +
      "tedBy\030P \001(\tB\r\n\013_submitTime*,\n\nStatusType" +
      "\022\007\n\003RUN\020\000\022\010\n\004STOP\020\001\022\013\n\007DELETED\020\0022\\\n\010gRPC" +
      "Demo\022$\n\010addEntry\022\016.AddOneRequest\032\006.OneVO" +
      "\"\000\022*\n\014searchByName\022\016.SearchRequest\032\006.One" +
      "VO\"\0000\001B&\n\"com.demo.newfeature.web.grpc.p" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AddOneRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddOneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddOneRequest_descriptor,
        new java.lang.String[] { "Name", "IntValue", "DecValue", });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Name", "Token", });
    internal_static_OneVO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OneVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OneVO_descriptor,
        new java.lang.String[] { "Id", "Name", "SubmitTime", "IntValue", "DecValue", "Status", "CreatedDate", "CreatedBy", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
