// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

// Protobuf Java Version: 3.25.8
package com.demo.newfeature.web.grpc.proto;

public interface OneVOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OneVO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 10;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 10;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 20;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 20;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int64 submitTime = 30;</code>
   * @return Whether the submitTime field is set.
   */
  boolean hasSubmitTime();
  /**
   * <code>optional int64 submitTime = 30;</code>
   * @return The submitTime.
   */
  long getSubmitTime();

  /**
   * <code>int32 intValue = 40;</code>
   * @return The intValue.
   */
  int getIntValue();

  /**
   * <code>float decValue = 50;</code>
   * @return The decValue.
   */
  float getDecValue();

  /**
   * <code>.StatusType status = 60;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.StatusType status = 60;</code>
   * @return The status.
   */
  com.demo.newfeature.web.grpc.proto.StatusType getStatus();

  /**
   * <code>int64 createdDate = 70;</code>
   * @return The createdDate.
   */
  long getCreatedDate();

  /**
   * <code>string createdBy = 80;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string createdBy = 80;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();
}
