// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.30.2

package com.demo.newfeature.web.grpc.proto;

/**
 * <pre>
 * The response message containing the greetings
 * </pre>
 *
 * Protobuf type {@code OneVO}
 */
public final class OneVO extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:OneVO)
    OneVOOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      OneVO.class.getName());
  }
  // Use OneVO.newBuilder() to construct.
  private OneVO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OneVO() {
    id_ = "";
    name_ = "";
    status_ = 0;
    createdBy_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.demo.newfeature.web.grpc.proto.Demo.internal_static_OneVO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.demo.newfeature.web.grpc.proto.Demo.internal_static_OneVO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.demo.newfeature.web.grpc.proto.OneVO.class, com.demo.newfeature.web.grpc.proto.OneVO.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 10;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 10;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 20;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 20;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 20;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBMITTIME_FIELD_NUMBER = 30;
  private long submitTime_ = 0L;
  /**
   * <code>optional int64 submitTime = 30;</code>
   * @return Whether the submitTime field is set.
   */
  @java.lang.Override
  public boolean hasSubmitTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 submitTime = 30;</code>
   * @return The submitTime.
   */
  @java.lang.Override
  public long getSubmitTime() {
    return submitTime_;
  }

  public static final int INTVALUE_FIELD_NUMBER = 40;
  private int intValue_ = 0;
  /**
   * <code>int32 intValue = 40;</code>
   * @return The intValue.
   */
  @java.lang.Override
  public int getIntValue() {
    return intValue_;
  }

  public static final int DECVALUE_FIELD_NUMBER = 50;
  private float decValue_ = 0F;
  /**
   * <code>float decValue = 50;</code>
   * @return The decValue.
   */
  @java.lang.Override
  public float getDecValue() {
    return decValue_;
  }

  public static final int STATUS_FIELD_NUMBER = 60;
  private int status_ = 0;
  /**
   * <code>.StatusType status = 60;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.StatusType status = 60;</code>
   * @return The status.
   */
  @java.lang.Override public com.demo.newfeature.web.grpc.proto.StatusType getStatus() {
    com.demo.newfeature.web.grpc.proto.StatusType result = com.demo.newfeature.web.grpc.proto.StatusType.forNumber(status_);
    return result == null ? com.demo.newfeature.web.grpc.proto.StatusType.UNRECOGNIZED : result;
  }

  public static final int CREATEDDATE_FIELD_NUMBER = 70;
  private long createdDate_ = 0L;
  /**
   * <code>int64 createdDate = 70;</code>
   * @return The createdDate.
   */
  @java.lang.Override
  public long getCreatedDate() {
    return createdDate_;
  }

  public static final int CREATEDBY_FIELD_NUMBER = 80;
  @SuppressWarnings("serial")
  private volatile java.lang.Object createdBy_ = "";
  /**
   * <code>string createdBy = 80;</code>
   * @return The createdBy.
   */
  @java.lang.Override
  public java.lang.String getCreatedBy() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdBy_ = s;
      return s;
    }
  }
  /**
   * <code>string createdBy = 80;</code>
   * @return The bytes for createdBy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedByBytes() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 20, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(30, submitTime_);
    }
    if (intValue_ != 0) {
      output.writeInt32(40, intValue_);
    }
    if (java.lang.Float.floatToRawIntBits(decValue_) != 0) {
      output.writeFloat(50, decValue_);
    }
    if (status_ != com.demo.newfeature.web.grpc.proto.StatusType.RUN.getNumber()) {
      output.writeEnum(60, status_);
    }
    if (createdDate_ != 0L) {
      output.writeInt64(70, createdDate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(createdBy_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 80, createdBy_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(20, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(30, submitTime_);
    }
    if (intValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(40, intValue_);
    }
    if (java.lang.Float.floatToRawIntBits(decValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(50, decValue_);
    }
    if (status_ != com.demo.newfeature.web.grpc.proto.StatusType.RUN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(60, status_);
    }
    if (createdDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(70, createdDate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(createdBy_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(80, createdBy_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.demo.newfeature.web.grpc.proto.OneVO)) {
      return super.equals(obj);
    }
    com.demo.newfeature.web.grpc.proto.OneVO other = (com.demo.newfeature.web.grpc.proto.OneVO) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasSubmitTime() != other.hasSubmitTime()) return false;
    if (hasSubmitTime()) {
      if (getSubmitTime()
          != other.getSubmitTime()) return false;
    }
    if (getIntValue()
        != other.getIntValue()) return false;
    if (java.lang.Float.floatToIntBits(getDecValue())
        != java.lang.Float.floatToIntBits(
            other.getDecValue())) return false;
    if (status_ != other.status_) return false;
    if (getCreatedDate()
        != other.getCreatedDate()) return false;
    if (!getCreatedBy()
        .equals(other.getCreatedBy())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasSubmitTime()) {
      hash = (37 * hash) + SUBMITTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSubmitTime());
    }
    hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getIntValue();
    hash = (37 * hash) + DECVALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDecValue());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + CREATEDDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedDate());
    hash = (37 * hash) + CREATEDBY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.demo.newfeature.web.grpc.proto.OneVO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.demo.newfeature.web.grpc.proto.OneVO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.newfeature.web.grpc.proto.OneVO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.demo.newfeature.web.grpc.proto.OneVO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code OneVO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OneVO)
      com.demo.newfeature.web.grpc.proto.OneVOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.newfeature.web.grpc.proto.Demo.internal_static_OneVO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.newfeature.web.grpc.proto.Demo.internal_static_OneVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.newfeature.web.grpc.proto.OneVO.class, com.demo.newfeature.web.grpc.proto.OneVO.Builder.class);
    }

    // Construct using com.demo.newfeature.web.grpc.proto.OneVO.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      submitTime_ = 0L;
      intValue_ = 0;
      decValue_ = 0F;
      status_ = 0;
      createdDate_ = 0L;
      createdBy_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.demo.newfeature.web.grpc.proto.Demo.internal_static_OneVO_descriptor;
    }

    @java.lang.Override
    public com.demo.newfeature.web.grpc.proto.OneVO getDefaultInstanceForType() {
      return com.demo.newfeature.web.grpc.proto.OneVO.getDefaultInstance();
    }

    @java.lang.Override
    public com.demo.newfeature.web.grpc.proto.OneVO build() {
      com.demo.newfeature.web.grpc.proto.OneVO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.demo.newfeature.web.grpc.proto.OneVO buildPartial() {
      com.demo.newfeature.web.grpc.proto.OneVO result = new com.demo.newfeature.web.grpc.proto.OneVO(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.demo.newfeature.web.grpc.proto.OneVO result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.submitTime_ = submitTime_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.intValue_ = intValue_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.decValue_ = decValue_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.createdDate_ = createdDate_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.createdBy_ = createdBy_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.demo.newfeature.web.grpc.proto.OneVO) {
        return mergeFrom((com.demo.newfeature.web.grpc.proto.OneVO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.demo.newfeature.web.grpc.proto.OneVO other) {
      if (other == com.demo.newfeature.web.grpc.proto.OneVO.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasSubmitTime()) {
        setSubmitTime(other.getSubmitTime());
      }
      if (other.getIntValue() != 0) {
        setIntValue(other.getIntValue());
      }
      if (java.lang.Float.floatToRawIntBits(other.getDecValue()) != 0) {
        setDecValue(other.getDecValue());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getCreatedDate() != 0L) {
        setCreatedDate(other.getCreatedDate());
      }
      if (!other.getCreatedBy().isEmpty()) {
        createdBy_ = other.createdBy_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 82
            case 162: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 162
            case 240: {
              submitTime_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 240
            case 320: {
              intValue_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 320
            case 405: {
              decValue_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 405
            case 480: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 480
            case 560: {
              createdDate_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 560
            case 642: {
              createdBy_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 642
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 10;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 10;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 10;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 10;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 20;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 20;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 20;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 20;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long submitTime_ ;
    /**
     * <code>optional int64 submitTime = 30;</code>
     * @return Whether the submitTime field is set.
     */
    @java.lang.Override
    public boolean hasSubmitTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 submitTime = 30;</code>
     * @return The submitTime.
     */
    @java.lang.Override
    public long getSubmitTime() {
      return submitTime_;
    }
    /**
     * <code>optional int64 submitTime = 30;</code>
     * @param value The submitTime to set.
     * @return This builder for chaining.
     */
    public Builder setSubmitTime(long value) {

      submitTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 submitTime = 30;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubmitTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      submitTime_ = 0L;
      onChanged();
      return this;
    }

    private int intValue_ ;
    /**
     * <code>int32 intValue = 40;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public int getIntValue() {
      return intValue_;
    }
    /**
     * <code>int32 intValue = 40;</code>
     * @param value The intValue to set.
     * @return This builder for chaining.
     */
    public Builder setIntValue(int value) {

      intValue_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 intValue = 40;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntValue() {
      bitField0_ = (bitField0_ & ~0x00000008);
      intValue_ = 0;
      onChanged();
      return this;
    }

    private float decValue_ ;
    /**
     * <code>float decValue = 50;</code>
     * @return The decValue.
     */
    @java.lang.Override
    public float getDecValue() {
      return decValue_;
    }
    /**
     * <code>float decValue = 50;</code>
     * @param value The decValue to set.
     * @return This builder for chaining.
     */
    public Builder setDecValue(float value) {

      decValue_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float decValue = 50;</code>
     * @return This builder for chaining.
     */
    public Builder clearDecValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      decValue_ = 0F;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.StatusType status = 60;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.StatusType status = 60;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.StatusType status = 60;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.demo.newfeature.web.grpc.proto.StatusType getStatus() {
      com.demo.newfeature.web.grpc.proto.StatusType result = com.demo.newfeature.web.grpc.proto.StatusType.forNumber(status_);
      return result == null ? com.demo.newfeature.web.grpc.proto.StatusType.UNRECOGNIZED : result;
    }
    /**
     * <code>.StatusType status = 60;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.demo.newfeature.web.grpc.proto.StatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.StatusType status = 60;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000020);
      status_ = 0;
      onChanged();
      return this;
    }

    private long createdDate_ ;
    /**
     * <code>int64 createdDate = 70;</code>
     * @return The createdDate.
     */
    @java.lang.Override
    public long getCreatedDate() {
      return createdDate_;
    }
    /**
     * <code>int64 createdDate = 70;</code>
     * @param value The createdDate to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedDate(long value) {

      createdDate_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 createdDate = 70;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedDate() {
      bitField0_ = (bitField0_ & ~0x00000040);
      createdDate_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object createdBy_ = "";
    /**
     * <code>string createdBy = 80;</code>
     * @return The createdBy.
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string createdBy = 80;</code>
     * @return The bytes for createdBy.
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string createdBy = 80;</code>
     * @param value The createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedBy(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      createdBy_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string createdBy = 80;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedBy() {
      createdBy_ = getDefaultInstance().getCreatedBy();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string createdBy = 80;</code>
     * @param value The bytes for createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      createdBy_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:OneVO)
  }

  // @@protoc_insertion_point(class_scope:OneVO)
  private static final com.demo.newfeature.web.grpc.proto.OneVO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.demo.newfeature.web.grpc.proto.OneVO();
  }

  public static com.demo.newfeature.web.grpc.proto.OneVO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OneVO>
      PARSER = new com.google.protobuf.AbstractParser<OneVO>() {
    @java.lang.Override
    public OneVO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OneVO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OneVO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.demo.newfeature.web.grpc.proto.OneVO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

