// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

// Protobuf Java Version: 3.25.8
package com.demo.newfeature.web.grpc.proto;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string token = 2;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
