// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.30.2

package com.demo.newfeature.web.grpc.proto;

/**
 * Protobuf enum {@code StatusType}
 */
public enum StatusType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RUN = 0;</code>
   */
  RUN(0),
  /**
   * <code>STOP = 1;</code>
   */
  STOP(1),
  /**
   * <code>DELETED = 2;</code>
   */
  DELETED(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      StatusType.class.getName());
  }
  /**
   * <code>RUN = 0;</code>
   */
  public static final int RUN_VALUE = 0;
  /**
   * <code>STOP = 1;</code>
   */
  public static final int STOP_VALUE = 1;
  /**
   * <code>DELETED = 2;</code>
   */
  public static final int DELETED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StatusType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static StatusType forNumber(int value) {
    switch (value) {
      case 0: return RUN;
      case 1: return STOP;
      case 2: return DELETED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StatusType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
          public StatusType findValueByNumber(int number) {
            return StatusType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.demo.newfeature.web.grpc.proto.Demo.getDescriptor().getEnumTypes().get(0);
  }

  private static final StatusType[] VALUES = values();

  public static StatusType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StatusType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:StatusType)
}

