spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: "localhost:9092"
    template:
      default-topic: "test-topic"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      default-topic: "test-topic"
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      default-topic: "test-topic"
      group-id: "test-group"
      isolation-level: "READ_COMMITTED"
logging:
  level:
    org.springframework.kafka: "trace"
    com.demo.kafka: "info"