spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      transaction-id-prefix: "tx-for-prod-${timestamp}"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      default-topic: "test-topic"
      properties:
        spring.json.trusted.packages: "com.demo.kafka.tools.entity"
        spring.json.type.mapping: "entity: com.demo.kafka.tools.entity.DataEntity, summary: com.demo.kafka.tools.entity.SummaryEntity"
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      default-topic: "test-topic"
      group-id: "test-group"
      isolation-level: "READ_COMMITTED"
      properties:
        spring.json.type.mapping: "entity: com.demo.kafka.tools.entity.DataEntity, summary: com.demo.kafka.tools.entity.SummaryEntity"
        spring.json.trusted.packages: "com.demo.kafka.tools.entity"
logging:
  root: "warn"
  level:
    org.springframework.kafka: "warn"
    com.demo.kafka: "info"
    org.apache.kafka: "warn"