spring:
  application:
    name: dubbo-client
dubbo:
  registry:
    address: 'nacos://localhost:8848?username=api_client&password=583R3hH_jLH2y_A'
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  config-center:
    group: demo
    address: 'nacos://localhost:8848?username=api_client&password=583R3hH_jLH2y_A'
    app-config-file: dubbo-app.properties # optional
  application:
    name: DemoDubboClient
    logger: slf4j
