CREATE TABLE T_ONE   (
ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 100) PRIMARY KEY,
NAME VARCHAR (50),
SUBMIT_TIME  TIMESTAMP,
INT_VAL  INTEGER,
DEC_VAL  DECIMAL(8,2),
CREATED_DATE TIMESTAMP default NOW(),
CREATED_BY VARCHAR(50),
VERSION INTEGER,
IS_DELETED BOOLEAN default false,
STATUS VARCHAR(10)
);
