spring:
  application:
    name: dubbo-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    #    url: jdbc:postgresql://localhost:5432/public
    username: test
    password: test_pwd
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.apache.dubbo.rpc.protocol.tri: debug
    org.apache.dubbo.remoting: debug
dubbo:
  config-center:
    group: demo
    address: 'nacos://localhost:8848?username=api_client&password=583R3hH_jLH2y_A'
    app-config-file: dubbo-app.properties # optional
    config-file: dubbo-env.properties
  #  protocol:
  #    name: tri
  #    port: 20800
  #    triple:
  #      verbose: true
  #    config-file: dubbo-env.properties
  application:
    name: DemoDubboService
    logger: slf4j
