server:
  port: 8000
  servlet:
    contextPath: /grpc
spring:
  application:
    name: demo-grpc
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    #    url: jdbc:postgresql://localhost:5432/public
    username: test
    password: test_pwd
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.cloud.task: "DEBUG"